PycharmProjects/website/users/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'
urlpatterns = [
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('blogpost/', blogpost, name='blogpost'),
    path('index/', index1, name='index1'),
    path('signup/', signup, name='signup'),
    path('user_signup/', user_signup, name='user_signup'),
    path('signup1/', signup1, name='signup1'),
    path('myblog/', MyBlogListView.as_view(), name='myblog'),
    path('blogs/', blog_View.as_view(), name='adminblog'),
    path('edit/<pk>/', blog_edit, name='blog_edit'),
    path('delete/<pk>/', blog_delete, name='blog_delete'),
    path('adminedit/<pk>/', admin_edit, name='admin_edit'),
    path('admindelete/<pk>/', admin_delete, name='admin_delete'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PycharmProjects/website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import *
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home1.html'), name='home'), # Add this
    path('users/', include(('users.urls', 'users'), namespace='users')),


]

PycharmProjects/website/login/models.py
from django.db import models

# Create your models here.

PycharmProjects/website/signup/models.py
from django.db import models

# Create your models here.

PycharmProjects/website/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, AbstractUser, UserManager
from django.core.validators import RegexValidator
from django.utils import timezone
import uuid
from django.contrib.auth.base_user import BaseUserManager

# Create your models here.

class Users (AbstractUser):

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    email = models.EmailField(
        verbose_name='email address',
        max_length=30,
        unique=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
            message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, unique=True)
    is_admin = models.IntegerField(default=0)
    is_deleted = models.BooleanField(default=False)
    modified_date = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"  # make the user log in with the email
    REQUIRED_FIELDS = ["username"]

    #objects = CustomUserManager()


    def __str__(self):
        return self.username


class User_details (models.Model):
    Male = 'M'
    FeMale = 'F'
    GENDER_CHOICES = (
        (Male, 'Male'),
        (FeMale, 'Female'),
    )
    user = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=20, null=False)
    last_name = models.CharField(max_length=20, null=False)
    age = models.IntegerField(null=False)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES,
                              default=Male)
    address = models.TextField(max_length=150, null=False)


class Post (models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, blank=True)
    blog_title = models.CharField(max_length=200, null=False)
    post_here = models.TextField(max_length=500, null=False)
    time_stamp = models.DateTimeField(default=timezone.now)
    posted_by = models.CharField(max_length=50, null=False)
    is_deleted = models.BooleanField(default=False)


class CustomUserManager(BaseUserManager):

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(
                "Superuser must have is_staff=True."
            )
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
                "Superuser must have is_superuser=True."
            )

        return self._create_user(email, password, **extra_fields)

PycharmProjects/website/users/forms.py
from django.forms import ModelForm, Form
from .models import Users, User_details, Post
from django import forms
from django.contrib.auth.forms import UserCreationForm



# define the class of a form
class RegistrationForm1(ModelForm):
    class Meta:
        # write the name of models for which the form is made
        model = User_details

        # Custom fields
        fields = ["first_name", "last_name", "age", "gender", "address", "user"]

    # this function will be used for the validation
    def clean(self):

        # data from the form is fetched using super function
        super(RegistrationForm1, self).clean()

        # extract the first_name from the data
        first_name = self.cleaned_data.get('first_name')
        age = self.cleaned_data.get('age')

        # conditions to be met for the first_name length
        if len(first_name) < 3:
            self._errors['first_name'] = self.error_class([
                'Minimum 3 characters required'])
        if age == 0:
            self.errors['age'] = self.error_class([
                'age cannot be 0'])

        # return any errors if found
        return self.cleaned_data


class RegistrationForm2(UserCreationForm):
    phone_number = forms.RegexField(regex=r'^\+?1?\d{9,15}$')
    class Meta:
        # write the name of models for which the form is made
        model = Users

        # Custom fields
        fields = ["username","email", "phone_number", "is_admin"]


class LogInForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


class PostForm(ModelForm):
    #user_id = forms.ModelChoiceField(queryset=Users.objects.filter())
    class Meta:
        model = Post

        fields = ["blog_title", "post_here"]
        exclude = ["user"]

PycharmProjects/website/login/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
import mysql.connector as sql

em = ''
pwd = ''


# Create your views here.
def loginaction(request):
    global em, pwd
    if request.method == "POST":
        m = sql.connect(host="127.0.0.1", user="root", passwd="", database='webdata')
        cursor = m.cursor()
        d = request.POST
        for key, value in d.items():
            if key == "email":
                em = value
            if key == "password":
                pwd = value

        c = "select * from users where email='{}' and password='{}'".format(em, pwd)
        cursor.execute(c)
        t = tuple(cursor.fetchall())
        if t == ():
            return render(request, 'error.html')
        else:
            return render(request, "blogpost.html")

    return render(request, 'login.html')

PycharmProjects/website/signup/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
import mysql.connector as sql

fn = ''
ln = ''
g = ''
a = ''
ad = ''
ph = ''
em = ''
pwd = ''


# Create your views here.
def signaction(request):
    global fn, ln, g, em, pwd
    if request.method == "POST":
        m = sql.connect(host="127.0.0.1", user="root", passwd="", database='webdata')
        cursor = m.cursor()
        d = request.POST
        for key, value in d.items():
            if key == "first_name":
                fn = value
            if key == "last_name":
                ln = value
            if key == "gender":
                g = value
            if key == "age":
                a = value
            if key == "address":
                ad = value
            if key == "phone_no":
                ph == value
            if key == "email":
                em = value
            if key == "password":
                pwd = value

        c = "insert into users Values('{}','{}','{}','{}','{}','{}','{}','{}')".format(fn, ln, g, a, ad, ph, em, pwd)
        cursor.execute(c)
        m.commit()

    return render(request, 'signup_page.html')

PycharmProjects/website/users/views.py
from .models import Users, User_details, Post
from .forms import RegistrationForm1, RegistrationForm2, LogInForm, PostForm
from . import views
from django.shortcuts import HttpResponse, render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout #add this
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib import messages
from django.urls import reverse
from django.views.generic.list import ListView
from django.http import JsonResponse
# Create your views here.

def signup1(request):
    # check if the request is post
    if request.method == 'POST':
        #current_user = request.user
        # Pass the form data to the form class
        details = RegistrationForm1(request.POST)

        if details.is_valid():

            # Temporarily make an object to be add some
            # logic into the data if there is such a need
            # before writing to the database
            post = details.save(commit=False)
            #post.user_id = current_user.id
            # Finally write the changes into database
            post.save()
            return JsonResponse({'statusCode': 200, 'message': "Details submitted Successfully"})

            # redirect it to some another page indicating data
            # was inserted successfully
            #return redirect(reverse('users:signup'))

        else:

            # Redirect back to the same page if the data
            # was invalid
            return render(request, "signup1.html", {'form': details})
    else:

        # If the request is a GET request then,
        # create an empty form object and
        # render it into the page
        form = RegistrationForm1(None)
        return render(request, 'signup1.html', {'form': form})

#
def signup(request):
    # check if the request is post
    if request.user.is_authenticated:
        return redirect(reverse('users:index1'))
    if request.method == 'POST':
        #if request.POST.get('submit') == 'Signup':
            # Pass the form data to the form class
        details  = RegistrationForm2(request.POST)

        if details.is_valid():
            details.save()
            return JsonResponse({'statusCode': 200, 'message': "Inserted Successfully"})
            #return redirect(reverse('users:signup1'))
            #     # Temporarily make an object to be add some
            #     # logic into the data if there is such a need
            #     # before writing to the database
            #     post = details.save(commit=False)
            # # Finally write the changes into database
            #     post.save()

                #return redirect(reverse('users:signup1'))


        elif request.POST.get('submit') == 'Login':
            form = LogInForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data["email"]
                password = form.cleaned_data["password"]
                try:
                    user = authenticate(request, email=email, password=password)
                except:
                    return JsonResponse({'statusCode': 401,"message": "Invalid credential"})
                if user is not None:
                    login(request, user)
                    return JsonResponse({'statusCode': 202,"message": "User Login Success"})
                else:
                    return JsonResponse({'statusCode': 401,"message": "Invalid credential"})


                #print(username, password)
                # user = authenticate(email=email, password=password)
                # if user:
                #     login(request, user)
                #     return redirect(reverse('users:index1'))
                # else:
                #     error = True

    else:
        return render(request, 'home1.html')


def user_signup(request):
    user = Users.objects.get(pk=45)
    print(type(user))
    json_user = {}
    json_user['email'] = user.email
    json_user['password'] = user.password
    json_user['username'] = user.username
    print(user)
    print(user.username)
    print(user.email)
    print(user.phone_number)
    exit()
    user = Users()
    user.username = request.POST['username']
    user.email = request.POST['email']
    user.phone_number=request.POST['phone_number']
    user.save()
    return JsonResponse({'statusCode': 200, 'message': "Inserted Successfully"})



def log_in(request):
    error = False
    if request.user.is_authenticated:
        return redirect(reverse('users:blogpost'))
        #return render(request, 'blogpost.html')
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect(reverse('users:blogpost'))
            else:
                error = True
    else:
        form = LogInForm()

    return render(request, 'home1.html', {'form': form, 'error': error})


def log_out(request):
    logout(request)
    return redirect(reverse('users:signup'))


def blogpost(request):
    error = False
    if request.method == "POST":
        current_user = request.user
        #ob = Users.objects.filter(id = current_user.id).first()
        #obj = Post(user = current_user.id)
        #obj = Post.objects.filter(user = current_user.id).first()
        details = PostForm(request.POST)
        if details.is_valid():
            post = details.save(commit=False)
            post.user_id = current_user.id
            post.posted_by = current_user
            post.save()
            return JsonResponse({'statusCode': 200, 'message': "Inserted Successfully"})
            #return redirect(reverse('users:blogpost'))
                #render(request, 'blogpost.html', {'form': details, 'error': error})
    else:
        form = PostForm()
        return render(request, 'blogpost.html', {'form': form, 'error': error})

    return redirect(reverse('users:blogpost'))


def index1(request):
    return render(request, 'index1.html')


class MyBlogListView(ListView):
    model = Post
    template_name = 'my_blog.html'
    context_object_name = "myblog"
    ordering = "-time_stamp"

    def get_queryset(self):
        return Post.objects.filter(user_id=self.request.user.id)



"""
class Admin_View(ListView):
    model = Post
    template_name = 'admin_blog.html'
    context_object_name = "adminblog"
    ordering = "-time_stamp"

    def get_queryset1(self):
        return Post.objects.filter(user_id=self.request.user.id)

"""
class blog_View(ListView):
    model = Post
    template_name = 'admin_blog.html'
    context_object_name = "adminblog"
    ordering = "-time_stamp"

    def get_queryset(self):
        if 1==self.request.user.is_admin:
            return Post.objects.all()
        else:
            return Post.objects.filter(user_id=self.request.user.id)


def blog_edit(request, pk):
    obj = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        post = PostForm(request.POST or None, instance=obj)
        if post.is_valid():
            post.save()
            return JsonResponse({'statusCode': 200, 'message': "Updated Successfully"})
            #return redirect(reverse('users:myblog'))
    else:
        form = PostForm(instance=obj)
        return render(request, "edit.html", {'form': form})


def blog_delete(request, pk):
    obj = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        details = PostForm(request.POST or None, instance=obj)
        if details.is_valid():
            post = details.save(commit=False)
            post.is_deleted = True
            post.save()
            return JsonResponse({'statusCode': 200, 'message': "Deleted Successfully"})
            #return redirect(reverse('users:myblog'))
    else:
        form = PostForm(instance=obj)
        return render(request, "delete.html", {'form': form})


def admin_edit(request, pk):
    obj = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        post = PostForm(request.POST or None, instance=obj)
        if post.is_valid():
            post.save()
            return JsonResponse({'statusCode': 200, 'message': "Updated Successfully"})
            #return redirect(reverse('users:adminblog'))
    else:
        form = PostForm(instance=obj)
        return render(request, "adminedit.html", {'form': form})

def admin_delete(request, pk):
    obj = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        details = PostForm(request.POST or None, instance=obj)
        if details.is_valid():
            post = details.save(commit=False)
            post.is_deleted = True
            post.save()
            return JsonResponse({'statusCode': 200, 'message': "Deleted Successfully"})
            #return redirect(reverse('users:adminblog'))
    else:
        form = PostForm(instance=obj)
        return render(request, "admindelete.html", {'form': form})

PycharmProjects/website/users/templates/admindelete.html
{% load bootstrap5 %}
{% bootstrap_messages %}

<html lang="en">

<head >

	<title>Delete Page</title>

	<meta charset="utf-8" />

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<style>
		 body{
                font-family: Arial, Helvetica, sans-serif;
                background-color: white;
            }
            button{
                background-color: #4CAF50;
                width: 25%;
                padding: 15px;
                color: black;
                border: none;
                float: center;
                font-size: 15px;
            }
            label{
                font-size: 20px;
            }
            form{
                border: 3px solid #f1f1f1;
            }
            input[type=email],input[type=text]{
                width: 50%;
                font-size: 15px;
                margin: 8px 0px;
                padding: 12px 20px;
                display: inline-block;
                border: 2px solid green;
                box-sizing: border-box;
            }
            input[type=radio]{
                height: 18px;
                width: 18px;
            }
            button:hover{
                opacity:0.7;

            }
            .container{
                padding: 50px;
                background-color: white;
            }
            .imgcontainer {
                text-align: center;
                margin: 24px 0 12px 0;
            }

            img.avatar {
                width: 10%;
                border-radius: 50%;
            }
	</style>

</head>

<body style="padding-top: 60px;background-color: #f5f7f8 !important;">
	<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
		<h2>Posts</h2>
			<form action="" method="post" id = "deleteForm"><input type='hidden'/>
			{%csrf_token %}

				{% bootstrap_form form %}

<!-This is the form variable which we are passing from the function
of home in views.py file. That's the beauty of Django we
don't need to write much codes in this it'll automatically pass
all the form details in here
->
			<div class="form-group">
				<button type="submit" class="btn btn-default ">
				Delete
				</button>

				</div>

				</form>
		</div>
		 <script src="https://code.jquery.com/jquery-3.6.0.js"
                    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

            <script>

               $(document).on('submit', '#deleteForm',function(e){

               e.preventDefault();
               var blog_title = $('#id_blog_title').val()
               console.log(blog_title);
               var post_here = $('#id_post_here').val()
               console.log(post_here);
               var url = $(location).attr("href");


               //ajax call

               $.ajax({

               type: 'POST',
               url: url,
               dataType:"json",
               data : {
                     blog_title :blog_title,
                     post_here :post_here,
                     csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val()
                     },
              success:function(response){
                      if (response.statusCode == 200) {
                        alert(response.message);
                        window.location.href = "{% url 'users:adminblog' %}";
                        //window.location.reload();
                      } else {
                        alert(response.message);
                      }

              }
              })
              });


              // Login

               </script>
	</div>
</div>

</body>

</html>

PycharmProjects/website/users/templates/blogpost.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% bootstrap_messages %}

{% block content %}
<html lang="en">

<head >

	<title>Index Page</title>

	<meta charset="utf-8" />

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>

<body style="padding-top: 0px;background-color: #f5f7f8 !important;">
	<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
		<h2>Posts</h2>
			<form action="" method="post" id="blogForm"><input type='hidden'/>
			{%csrf_token %}

				{% bootstrap_form form %}
<!-This is the form variable which we are passing from the function
of home in views.py file. That's the beauty of Django we
don't need to write much codes in this it'll automatically pass
all the form details in here
->
			<div class="form-group">
				<button type="submit" class="btn btn-default ">
				Submit
				</button>

				</div>

				</form>
			<script src="https://code.jquery.com/jquery-3.6.0.js"
                    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

            <script>

               $(document).on('submit', '#blogForm',function(e){

               e.preventDefault();
               var blog_title = $('#id_blog_title').val()
               console.log(blog_title);
               var post_here = $('#id_post_here').val()
               console.log(post_here);
               var url = $(location).attr("href");


               //ajax call

               $.ajax({

               type: 'POST',
               url: url,
               dataType:"json",
               data : {
                     blog_title :blog_title,
                     post_here :post_here,
                     csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val()
                     },
              success:function(response){
                      if (response.statusCode == 200) {
                        alert(response.message);
                        //window.location.href = "{% url 'users:myblog' %}";
                        window.location.reload();
                      } else {
                        alert(response.message);
                      }

              }
              })
              });


              // Login

               </script>
		</div>
	</div>
</div>

</body>

</html>

{% endblock content %}

PycharmProjects/website/users/templates/signup1.html
{% load bootstrap5 %}
{% bootstrap_messages %}
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <title>Login and Registration Form</title>
      <link rel="stylesheet" type="text/css" href="style.css" media="screen">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <style>
{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
html,body{
  display: grid;
  height: 100%;
  width: 100%;
  place-items: center;
  background: -webkit-linear-gradient(right,#7b2681, #230435, #7b2681);
}
::selection{
  background: #fa4299;
  color: #fff;
}
.wrapper{
  overflow: hidden;
  max-width: 390px;
  background: #e2bae8;
  padding: 30px;
  border-radius: 5px;
  box-shadow: 0px 15px 20px rgba(0,0,0,0.1);
}
.wrapper .title-text{
  display: flex;
  width: 200%;
}
.wrapper .title{
  width: 50%;
  font-size: 35px;
  font-weight: 600;
  text-align: center;
  transition: all 0.6s cubic-bezier(0.68,-0.55,0.265,1.55);
}
.wrapper .slide-controls{
  position: relative;
  display: flex;
  height: 50px;
  width: 100%;
  overflow: hidden;
  margin: 30px 0 10px 0;
  justify-content: space-between;
  border: 1px solid lightgrey;
  border-radius: 5px;
}
.slide-controls .slide{
  height: 100%;
  width: 100%;
  color: #fff;
  font-size: 18px;
  font-weight: 500;
  text-align: center;
  line-height: 48px;
  cursor: pointer;
  z-index: 1;
  transition: all 0.6s ease;
}
.slide-controls label.signup{
  color: #000;
}
.slide-controls .slider-tab{
  position: absolute;
  height: 100%;
  width: 100%;
  left: 0;
  z-index: 0;
  border-radius: 5px;
  background: -webkit-linear-gradient(left, #a445b2, #fa4299);
  transition: all 0.6s cubic-bezier(0.68,-0.55,0.265,1.55);
}
input[type="radio"]{
  display: none;
}

.wrapper .form-container{
  width: 100%;
  overflow: hidden;
}
.form-container .form-inner{
  display: flex;
  width: 200%;
}
.form-container .form-inner form{
  width: 50%;
  transition: all 0.6s cubic-bezier(0.68,-0.55,0.265,1.55);
}
.form-inner form .field{
  height: 50px;
  width: 100%;
  margin-top: 20px;
}
.form-inner form .field input{
  height: 100%;
  width: 100%;
  outline: none;
  padding-left: 15px;
  border-radius: 5px;
  border: 1px solid lightgrey;
  border-bottom-width: 2px;
  font-size: 17px;
  transition: all 0.3s ease;
}
.form-inner form .field input:focus{
  border-color: #fc83bb;
  /* box-shadow: inset 0 0 3px #fb6aae; */
}
.form-inner form .field input::placeholder{
  color: #999;
  transition: all 0.3s ease;
}
form .field input:focus::placeholder{
  color: #b3b3b3;
}
.form-inner form .pass-link{
  margin-top: 5px;
}
.form-inner form .signup-link{
  text-align: center;
  margin-top: 30px;
}
.form-inner form .pass-link a,
.form-inner form .signup-link a{
  color: #fa4299;
  text-decoration: none;
}
.form-inner form .pass-link a:hover,
.form-inner form .signup-link a:hover{
  text-decoration: underline;
}
form .btn{
  height: 50px;
  width: 100%;
  border-radius: 5px;
  position: relative;
  overflow: hidden;
}
form .btn .btn-layer{
  height: 100%;
  width: 300%;
  position: absolute;
  left: -100%;
  background: -webkit-linear-gradient(right, #a445b2, #fa4299, #a445b2, #fa4299);
  border-radius: 5px;
  transition: all 0.4s ease;;
}
form .btn:hover .btn-layer{
  left: 0;
}
form .btn input[type="submit"]{
  height: 100%;
  width: 100%;
  z-index: 1;
  position: relative;
  background: none;
  border: none;
  color: #fff;
  padding-left: 0;
  border-radius: 5px;
  font-size: 20px;
  font-weight: 500;
  cursor: pointer;
}
</style>
   </head>
   <body>
      <div class="wrapper">
         <div class="title-text">
            <div class="title details">
               Personal Details
            </div>
            <div class="title signup">
               Signup Form
            </div>
         </div>
         <div class="form-container">
            <div class="slide-controls">
               <input type="radio" name="slide" id="details" >
               <label for="details" class="slide signup">Details</label>
               <div class="slider-tab"></div>
            </div>
            <div class="form-inner">
               <form action="{% url 'users:signup1' %}" method="POST" class="details" id = "detailsForm">

                  {%csrf_token %}

                  <div class="field">
                     <input type="text" placeholder="First Name" name="first_name" required  id="id_first_name">
                  </div>
                  <div class="field">
                     <input type="text" placeholder="Last Name" name="last_name" required id="id_last_name">
                  </div>
                  <div class="field">
                     <input type="number" placeholder="Age" name="age" required id="id_age"><br>
                  </div>
                  <div class="field">
                     <input type="text" placeholder="Address" name="address" required id="id_address">
                  </div>
                  <div class="field">
                     {{ form.gender }}
                     {{ form.user }}
                  </div>

                  <div class="field btn">
                     <div class="btn-layer"></div>
                     <input type="submit" name='submit' value="Submit">
                  </div>
               </form>
            </div>
            <script src="https://code.jquery.com/jquery-3.6.0.js"
                    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

            <script>

               $(document).on('submit', '#detailsForm',function(e){

               e.preventDefault();
               var first_name = $('#id_first_name').val()
               console.log(first_name);
               var last_name = $('#id_last_name').val()
               console.log(last_name);
               var age = $('#id_age').val()
               var address = $('#id_address').val()
               var gender = $('#id_gender').val()
               var user = $('#id_user').val()


               //ajax call

               $.ajax({

               type: 'POST',
               url: '/users/signup1/',
               dataType:"json",
               data : {
                     first_name :first_name,
                     last_name :last_name,
                     age :age,
                     gender :gender,
                     address :address,
                     user :user,
                     csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val()
                     },
              success:function(response){
                      if (response.statusCode == 200) {
                        alert(response.message);
                        window.location.href = "{% url 'users:signup' %}";
                        //window.location.reload();
                      } else {
                        alert(response.message);
                      }

              }
              })
              });


              // Login

               </script>


         </div>
      </div>

   </body>
</html>